### ISSUE TITLE
Gives this error

### ISSUE THREAD

**Issue by Eikosa** [GitHub30/winocr#1]
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code  
    exec(code, run_globals)
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main  
    run()
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))  File "C:\Program Files\Python39\lib\runpy.py", line 268, in run_path  
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code  
    exec(code, run_globals)
  File "c:\Users\USER\AppData\Roaming\Python\Python39\site-packages\winocr.py", line 2, in <module>
    from winrt.windows.media.ocr import OcrEngine
  File "c:\Users\USER\AppData\Roaming\Python\Python39\site-packages\winrt\__init__.py", line 4, in <module>
    _winrt.init_apartment()
RuntimeError: İş parçacığı modu kurulduktan sonra değiştirilemez.
```
when trying to import winocr on visual studio code

**Comment by GitHub30** [comment]
https://github.com/microsoft/xlang/issues/690
